import json
import logging
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)


def generate_report(result: dict, query: str, output_path: str | None = None) -> str:
    """
    Generate a formatted Markdown report from analysis results.

    Args:
        result: The dict returned by FinancialAnalysisSystem.analyze().
        query: The original user query.
        output_path: Optional file path to save the report. If None, returns string only.

    Returns:
        The report as a Markdown string.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines.append("# Financial Analysis Report")
    lines.append(f"\n**Generated:** {timestamp}")
    lines.append(f"\n**Query:** {query}")

    # Error case
    if "error" in result:
        lines.append(f"\n## Error\n\n{result['error']}")
        return _finalize(lines, output_path)

    # Summary
    if result.get("summary"):
        lines.append(f"\n## Summary\n\n{result['summary']}")

    # Confidence
    if result.get("confidence"):
        lines.append(f"\n**Confidence:** {result['confidence']}")

    # Key Findings
    if result.get("key_findings"):
        lines.append("\n## Key Findings\n")
        for finding in result["key_findings"]:
            lines.append(f"- {finding}")

    # Extracted Data
    extracted = result.get("extracted_data", {})
    if extracted and "raw_response" not in extracted:
        lines.append("\n## Extracted Data\n")
        if extracted.get("company"):
            lines.append(f"**Company:** {extracted['company']}")
        if extracted.get("period"):
            lines.append(f"**Period:** {extracted['period']}")

        metrics = extracted.get("metrics", {})
        if metrics:
            lines.append("\n| Metric | Value | Period |")
            lines.append("|--------|-------|--------|")
            for name, detail in metrics.items():
                if isinstance(detail, dict) and "value" in detail:
                    val = detail.get("value", "N/A")
                    unit = detail.get("unit", "")
                    period = detail.get("period", "")
                    lines.append(f"| {name} | {val} {unit} | {period} |")

    # Trends
    trends = result.get("trends", {})
    if trends and "raw_response" not in trends:
        trend_list = trends.get("trends", [])
        if trend_list:
            lines.append("\n## Trends\n")
            lines.append("| Metric | Direction | Magnitude | Period |")
            lines.append("|--------|-----------|-----------|--------|")
            for t in trend_list:
                lines.append(
                    f"| {t.get('metric', '')} | {t.get('direction', '')} "
                    f"| {t.get('magnitude', '')} | {t.get('period', '')} |"
                )

        if trends.get("outlook"):
            lines.append(f"\n**Outlook:** {trends['outlook']}")

        anomalies = trends.get("anomalies", [])
        if anomalies:
            lines.append("\n### Anomalies\n")
            for a in anomalies:
                lines.append(f"- **{a.get('severity', 'unknown')}:** {a.get('description', '')}")

    # Sentiment
    sentiment = result.get("sentiment", {})
    if sentiment and "raw_response" not in sentiment:
        lines.append("\n## Sentiment Analysis\n")
        lines.append(f"**Overall:** {sentiment.get('overall_sentiment', 'N/A')}")

        pos = sentiment.get("positive_signals", [])
        if pos:
            lines.append("\n**Positive Signals:**")
            for s in pos:
                lines.append(f"- {s}")

        neg = sentiment.get("negative_signals", [])
        if neg:
            lines.append("\n**Negative Signals:**")
            for s in neg:
                lines.append(f"- {s}")

        if sentiment.get("forward_guidance"):
            lines.append(f"\n**Forward Guidance:** {sentiment['forward_guidance']}")

    # Validation
    validation = result.get("validation", {})
    if validation and "raw_response" not in validation:
        lines.append("\n## Validation\n")
        consistent = validation.get("is_consistent")
        if consistent is not None:
            status = "Consistent" if consistent else "Inconsistencies found"
            lines.append(f"**Status:** {status}")

        issues = validation.get("issues", [])
        if issues:
            lines.append("\n**Issues:**")
            for issue in issues:
                lines.append(
                    f"- [{issue.get('severity', '')}] {issue.get('description', '')}"
                )

        lines.append(f"\n**Recommendation:** {validation.get('recommendation', 'N/A')}")

    lines.append("\n---\n*Generated by Multi-Agent Financial Analysis System*")

    return _finalize(lines, output_path)


def _finalize(lines: list[str], output_path: str | None) -> str:
    """Join lines and optionally write to file."""
    report = "\n".join(lines)

    if output_path:
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(report, encoding="utf-8")
        logger.info(f"Report saved to {output_path}")

    return report
